# Linksys Velop services

delete_device:
  fields:
    mesh:
      name: Mesh
      description: The Mesh that the action should be executed on
      required: true
      selector:
        device:
          integration: linksys_velop
          manufacturer: uvjim
    device:
      name: Device
      description: The name or identifier of the device to rename
      required: true
      selector:
        text:

device_internet_access:
  fields:
    mesh:
      name: Mesh
      description: The Mesh that the action should be executed on
      required: true
      selector:
        device:
          integration: linksys_velop
          manufacturer: uvjim
    device:
      name: Device
      description: The name or identifier of the device to pause/resume
      required: true
      selector:
        text:
    pause:
      name: Pause Access
      description: Enable to pause Internet access for the device
      required: true
      selector:
        boolean:

device_internet_rules:
  fields:
    mesh:
      name: Mesh
      description: The Mesh that the action should be executed on
      required: true
      selector:
        device:
          integration: linksys_velop
          manufacturer: uvjim
    device:
      name: Device
      description: The name or identifier of the device to apply the schedule to
      required: true
      selector:
        text:
    sunday:
      name: Sunday
      description: Select times the device should be blocked
      required: false
      selector:
        select:
          mode: dropdown
          multiple: true
          options: !include includes/schedule_times.yaml
          translation_key: pc_times
    monday:
      name: Monday
      description: Select times the device should be blocked
      required: false
      selector:
        select:
          mode: dropdown
          multiple: true
          options: !include includes/schedule_times.yaml
          translation_key: pc_times
    tuesday:
      name: Tuesday
      description: Select times the device should be blocked
      required: false
      selector:
        select:
          mode: dropdown
          multiple: true
          options: !include includes/schedule_times.yaml
          translation_key: pc_times
    wednesday:
      name: Wednesday
      description: Select times the device should be blocked
      required: false
      selector:
        select:
          mode: dropdown
          multiple: true
          options: !include includes/schedule_times.yaml
          translation_key: pc_times
    thursday:
      name: Thursday
      description: Select times the device should be blocked
      required: false
      selector:
        select:
          mode: dropdown
          multiple: true
          options: !include includes/schedule_times.yaml
          translation_key: pc_times
    friday:
      name: Friday
      description: Select times the device should be blocked
      required: false
      selector:
        select:
          mode: dropdown
          multiple: true
          options: !include includes/schedule_times.yaml
          translation_key: pc_times
    saturday:
      name: Saturday
      description: Select times the device should be blocked
      required: false
      selector:
        select:
          mode: dropdown
          multiple: true
          options: !include includes/schedule_times.yaml
          translation_key: pc_times

reboot_node:
  fields:
    mesh:
      name: Mesh
      description: The Mesh that the action should be executed on
      required: true
      selector:
        device:
          integration: linksys_velop
          manufacturer: uvjim
    node_name:
      name: "Name"
      description: The name of the node to reboot
      required: true
      selector:
        text:
    is_primary:
      name: "Is Primary"
      description:
        Rebooting the primary node will force a reboot on all secondary nodes.
        If you are sure you want to do this, enable this setting and turn it on.
      required: false
      selector:
        boolean:

rename_device:
  fields:
    mesh:
      name: Mesh
      description: The Mesh that the action should be executed on
      required: true
      selector:
        device:
          integration: linksys_velop
          manufacturer: uvjim
    device:
      name: Device
      description: The name or identifier of the device to rename
      required: true
      selector:
        text:
    new_name:
      name: New Name
      description: The new name for the device
      required: true
      selector:
        text: